apiVersion: v2
name: jitsi-meet
type: application
description: Jitsi Meet packaged for Kubernetes
icon: https://jitsi-contrib.github.io/jitsi-helm/jitsi-meet.png

# This is the *chart* version.
# This version number should be incremented each time you make
# changes to the chart and its templates, including the app version.
version: 2.6.0

# This is the *application* version.
# If tags are not set explicitly in values.yaml then appVersion is used as
# the default tag for Jitsi images.
appVersion: stable-10741

## Chart annotations (for ArtifactHub):
annotations:
  artifacthub.io/category: streaming-messaging
  artifacthub.io/links: |
    - name: Jitsi Meet
      url: https://jitsi.org/jitsi-meet/
    - name: Jitsi Meet Documentation
      url: https://jitsi.github.io/handbook/docs/intro/
    - name: Jitsi-Helm GitHub
      url: https://github.com/jitsi-contrib/jitsi-helm
