{{- if .Values.jicofo.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.jicofo.fullname" . }}-metrics
  labels:
  {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-metrics
      port: 9996
      targetPort: 9996
  selector:
  {{- include "jitsi-meet.jicofo.selectorLabels" . | nindent 4 }}
{{- end }}
