{{- if empty .Values.jicofo.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.jicofo.secret" . }}
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
type: Opaque
data:
  JICOFO_AUTH_USER: '{{ b64enc "focus" }}'
  JICOFO_AUTH_PASSWORD: '{{ default (randAlphaNum 10) .Values.jicofo.xmpp.password | b64enc }}'
  JICOFO_COMPONENT_SECRET: '{{ default (randAlphaNum 10) .Values.jicofo.xmpp.componentSecret | b64enc }}'
{{- end }}
