{{- if not .Values.global.jicofo.xmpp.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jicofo
  labels:
    {{- include "jitsi-meet.jicofo.labels" . | nindent 4 }}
type: Opaque
data:
  JICOFO_AUTH_USER: '{{ b64enc "focus" }}'
  JICOFO_AUTH_PASSWORD: '{{ default (randAlphaNum 10) .Values.global.jicofo.xmpp.password | b64enc }}'
  JICOFO_COMPONENT_SECRET: '{{ default (randAlphaNum 10) .Values.global.jicofo.xmpp.componentSecret | b64enc }}'
{{- end }}
