{{- if .Values.opusTranscriberProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.opus-transcriber-proxy.fullname" . }}
  labels:
    {{- include "jitsi-meet.opus-transcriber-proxy.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.opusTranscriberProxy.service.port | quote }}
  HOST: {{ .Values.opusTranscriberProxy.host | quote }}

  {{- range $key, $value := .Values.opusTranscriberProxy.extraEnvs }}
  {{-   if not (kindIs "invalid" $value) }}
  {{      $key }}: {{ tpl (toString $value) $ | quote }}
  {{-   end }}
  {{- end }}
{{- end }}
