{{- if and
       .Values.opusTranscriberProxy.enabled
       (not .Values.opusTranscriberProxy.existingSecretName)
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.opus-transcriber-proxy.secret" . }}
  labels:
    {{- include "jitsi-meet.opus-transcriber-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.opusTranscriberProxy.apiKeys }}
  {{-   if not (kindIs "invalid" $value) }}
  {{      $key }}: {{ tpl $value $ | quote }}
  {{-   end }}
  {{- end }}
{{- end }}
