{{- if and
       .Values.jigasi.enabled
       (not .Values.jigasi.useExternalJigasi)
       (or
          .Values.jigasi.custom.defaults._autoscaler_sidecar_config
          .Values.jigasi.custom.defaults._logging_properties
          .Values.jigasi.custom.defaults._sip_communicator_properties
          .Values.jigasi.custom.defaults._sipserver_sip_communicator_properties
          .Values.jigasi.custom.defaults._transcriber_sip_communicator_properties
          .Values.jigasi.custom.defaults._xmpp_sip_communicator_properties
       )
}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jigasi.fullname" . }}-defaults
  labels:
    {{- include "jitsi-meet.jigasi.labels" . | nindent 4 }}
data:
  {{- with .Values.jigasi.custom.defaults._autoscaler_sidecar_config }}
  autoscaler-sidecar.config: |
    {{- . | nindent 4 }}
  {{- end }}

  {{- with .Values.jigasi.custom.defaults._logging_properties }}
  logging.properties: |
    {{- . | nindent 4 }}
  {{- end }}

  {{- with .Values.jigasi.custom.defaults._sip_communicator_properties }}
  sip-communicator.properties: |
    {{- . | nindent 4 }}
  {{- end }}

  {{- with .Values.jigasi.custom.defaults._sipserver_sip_communicator_properties }}
  sipserver-sip-communicator.properties: |
    {{- . | nindent 4 }}
  {{- end }}

  {{- with .Values.jigasi.custom.defaults._transcriber_sip_communicator_properties }}
  transcriber-sip-communicator.properties: |
    {{- . | nindent 4 }}
  {{- end }}

  {{- with .Values.jigasi.custom.defaults._xmpp_sip_communicator_properties }}
  xmpp-sip-communicator.properties: |
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
