{{- if empty .Values.jigasi.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.jigasi.secret" . }}
  labels:
    {{- include "jitsi-meet.jigasi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.jigasi.enabled }}
  JIGASI_XMPP_USER: '{{ .Values.jigasi.xmpp.user | b64enc }}'
  JIGASI_XMPP_PASSWORD: '{{ default (randAlphaNum 10) .Values.jigasi.xmpp.password | b64enc }}'
  {{- end }}
{{- end }}
