{{- if and (.Values.jibri.metrics.enabled) (.Values.jibri.metrics.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "jitsi-meet.jibri.fullname" . }}
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
    {{- with .Values.jibri.metrics.serviceMonitor.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - port: tcp-metrics
      path: /metrics
      interval: 15s
      {{- with .Values.jibri.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .Values.jibri.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
  selector:
    matchLabels:
        {{- include "jitsi-meet.jibri.selectorLabels" . | nindent 8 }}
      {{- range $label, $value := mergeOverwrite .Values.global.podLabels .Values.jibri.podLabels }}
        {{ $label }}: {{ $value }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end -}}
