{{- if and .Values.jibri.enabled .Values.jibri.persistence.enabled (not .Values.jibri.persistence.existingClaim) (not .Values.jibri.useExternalJibri) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jitsi-meet.jibri.fullname" . }}
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.jibri.persistence.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.jibri.persistence.size | quote }}
  {{- with .Values.jibri.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end -}}

{{- if and .Values.jibri.enabled (not .Values.jibri.useExternalJibri) .Values.jibri.s3.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jitsi-meet.jibri.fullname" . }}-aws
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"  # Run before the Job
spec:
  accessModes:
    - {{ .Values.jibri.s3.accessModes | quote }}
  resources:
    requests:
      storage: 400Mi
{{- end -}}      