{{- if and
       .Values.jibri.enabled
       (not .Values.jibri.xmpp.existingSecretName)
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.jibri.xmppSecret" . }}
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
type: Opaque
stringData:
  JIBRI_XMPP_USER: {{ .Values.jibri.xmpp.user | quote }}
  JIBRI_XMPP_PASSWORD: {{ .Values.jibri.xmpp.password | default (randAlphaNum 10) | quote }}
{{- end }}
