apiVersion: v1
kind: Secret
metadata:
  name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jibri
  labels:
    {{- include "jitsi-meet.jibri.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.jibri.enabled }}
  JIBRI_XMPP_USER: '{{ .Values.jibri.xmpp.user | b64enc }}'
  JIBRI_XMPP_PASSWORD: '{{ default (randAlphaNum 10) .Values.jibri.xmpp.password | b64enc }}'
  JIBRI_RECORDER_USER: '{{ .Values.jibri.recorder.user | b64enc }}'
  JIBRI_RECORDER_PASSWORD: '{{ default (randAlphaNum 10) .Values.jibri.recorder.password | b64enc }}'
{{- end }}
