{{- if and
       .Values.coturn.enabled
       (not .Values.coturn.staticAuth.existingSecretName)
}}
{{- $secretName := include "jitsi-meet.coturn.secret" . }}
{{- $kept := include "jitsi-meet.existingSecretValue"
      (dict "ctx" $ "name" $secretName "key" "TURN_CREDENTIALS") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "jitsi-meet.coturn.labels" . | nindent 4 }}
type: Opaque
stringData:
  TURN_CREDENTIALS: {{ .Values.coturn.staticAuth.secret
                       | default $kept
                       | default (randAlphaNum 10)
                       | quote }}
{{- end }}
