apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
data:
  DISABLE_HTTPS: {{ .Values.web.httpsEnabled | ternary "0" "1" | quote }}
  ENABLE_HTTP_REDIRECT: {{ .Values.web.httpRedirect | ternary "true" "false" | quote }}
  XMPP_BOSH_URL_BASE: 'http://{{ include "jitsi-meet.xmpp.server" . }}:{{ index .Values.prosody.service.ports "bosh-insecure" }}'

  {{- if .Values.excalidraw.enabled }}
  WHITEBOARD_COLLAB_SERVER_URL_BASE: 'http://{{ include "jitsi-meet.excalidraw.fullname" . }}:{{ .Values.excalidraw.service.port}}'
  {{- end }}

  {{- if .Values.etherpad.enabled }}
  ETHERPAD_URL_BASE: 'http://{{ include "jitsi-meet.etherpad.fullname" . }}:{{ .Values.etherpad.service.port}}'
  {{- end }}

  {{- if .Values.transcriber.enabled }}
  ENABLE_TRANSCRIPTIONS: "true"
  {{- end }}

  {{- with .Values.web.resolverIP }}
  NGINX_RESOLVER: {{ . }}
  {{- end }}

  {{- range $key, $value := .Values.web.extraEnvs }}
  {{-   if not (kindIs "invalid" $value) }}
  {{      $key }}: {{ tpl $value $ | quote }}
  {{-   end }}
  {{- end }}
