{{- if .Values.web.gateway.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
  {{- with .Values.web.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.web.gateway.gatewayClassName | quote }}
  listeners:
    {{- if .Values.web.gateway.tls.enabled }}
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.web.gateway.host | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.web.gateway.tls.secretName | quote }}
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    - name: http
      port: 80
      protocol: HTTP
      hostname: {{ .Values.web.gateway.host | quote }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
