{{- if and
       .Values.transcriber.enabled
       (not .Values.transcriber.useExternalTranscriber)
       .Values.transcriber.custom.scripts._config
}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.transcriber.fullname" . }}-scripts
  labels:
    {{- include "jitsi-meet.transcriber.labels" . | nindent 4 }}
data:
  config: |
    {{- .Values.transcriber.custom.scripts._config | nindent 4 }}
{{- end }}
