apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-transcriber
type: Opaque
data:
  {{- if .Values.transcriber.enabled }}
  JIGASI_TRANSCRIBER_USER: {{ .Values.transcriber.xmpp.user | b64enc | quote }}
  JIGASI_TRANSCRIBER_PASSWORD: {{ default (randAlphaNum 10) .Values.transcriber.xmpp.password | b64enc | quote }}
  {{- if not .Values.jigasi.enabled }}
  JIGASI_XMPP_USER: {{ .Values.jigasi.xmpp.user | b64enc | quote }}
  JIGASI_XMPP_PASSWORD: {{ default (randAlphaNum 10) .Values.jigasi.xmpp.password | b64enc | quote }}
  {{- end }}
  {{- end }}

