{{- if and
       .Values.prosody.jwt.secret
       (not .Values.prosody.jwt.existingSecretName)
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.prosody.secret" . }}
  labels:
    {{- include "jitsi-meet.prosody.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_APP_SECRET: {{ .Values.prosody.jwt.secret | quote }}
{{- end }}
