{{- if .Values.jvb.custom.scripts._config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" . }}-scripts
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
data:
  config: |
    {{- .Values.jvb.custom.scripts._config | nindent 4 }}
{{- end }}
