{{- if and (.Values.jvb.metrics.enabled) (.Values.jvb.metrics.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "jitsi-meet.jvb.fullname" . }}
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.jvb.metrics.serviceMonitor.selector }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  endpoints:
    - port: metrics
      {{- if .Values.jvb.metrics.serviceMonitor.interval }}
      interval: {{ .Values.jvb.metrics.serviceMonitor.interval }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "jitsi-meet.jvb.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end -}}
