{{- if empty .Values.jvb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi-meet.jvb.secret" . }}
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
type: Opaque
data:
  JVB_AUTH_USER: '{{ .Values.jvb.xmpp.user | b64enc }}'
  JVB_AUTH_PASSWORD: '{{ default (randAlphaNum 10) .Values.jvb.xmpp.password | b64enc }}'
{{- end }}
