{{- if not .Values.global.jvb.xmpp.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-jvb
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
type: Opaque
data:
  JVB_AUTH_USER: '{{ .Values.global.jvb.xmpp.user | b64enc }}'
  JVB_AUTH_PASSWORD: '{{ default (randAlphaNum 10) .Values.global.jvb.xmpp.password | b64enc }}'
{{- end }}
