{
 "title": "Jitsi Meet & System for Kubernetes/Prometheus",
 "description": "Dashboard for Jitsi Meet Exporter running on Kubernetes",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jitsi_conferences, instance)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU by component",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"shard-0-web-[^-]*-[^-]*$\", image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "web"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"shard-0-prosody-[^-]*-[^-]*$\", image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "prosody"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"shard-0-jicofo-[^-]*-[^-]*$\", image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "jicofo"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"shard-0-jvb-[^-]*-[^-]*$\", image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "jvb"
    }
   ]
  },
  {
   "title": "RAM by component",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"shard-0-web-[^-]*-[^-]*$\", image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "web"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"shard-0-prosody-[^-]*-[^-]*$\", image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "prosody"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"shard-0-jicofo-[^-]*-[^-]*$\", image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "jicofo"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"shard-0-jvb-[^-]*-[^-]*$\", image!=\"\", container_name!=\"POD\"}[5m]))",
     "legendFormat": "jvb"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "graph",
   "description": "The total incoming/outgoing bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_colibri_bit_rate_download{instance=~\"$instance.*\"})",
     "legendFormat": "download"
    },
    {
     "expr": "sum(jitsi_colibri_bit_rate_upload{instance=~\"$instance.*\"})",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Jitsi stress level",
   "type": "graph",
   "description": "Stress Level used by the JVB HPA",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_colibri_stress_level{instance=~\"$instance.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "jitsi_colibri_stress_level{instance=~\"$instance.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster used CPU",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (pod_name)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Cluster Used Memory",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sum(node_memory_MemAvailable_bytes{instance=~\"$instance.*\"}) * 100) / sum(node_memory_MemTotal_bytes{instance=~\"$instance.*\"}))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Transfered data volume",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes:rate:sum{instance=~\"$instance.*\"}",
     "legendFormat": "Incoming "
    }
   ]
  },
  {
   "title": "Bitrate Download",
   "type": "stat",
   "description": "The total incoming bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_colibri_bit_rate_download{instance=~\"$instance.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Bitrate Upload",
   "type": "stat",
   "description": "The total outgoing bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_colibri_bit_rate_upload{instance=~\"$instance.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of Java threads that the video bridge is using.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_colibri_threads{instance=~\"$instance.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Videostreams",
   "type": "stat",
   "description": "An estimation of the number of current video streams forwarded by the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_colibri_videostreams{instance=~\"$instance.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "RTT",
   "type": "stat",
   "description": "An average value (in milliseconds) of the RTT across all streams.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_colibri_rtt_aggregate{instance=~\"$instance.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Completed Conferences",
   "type": "stat",
   "description": "The sum of the lengths of all completed conferences, in seconds.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_colibri_total_conference_seconds{instance=~\"$instance.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Biggest Conference",
   "type": "stat",
   "description": "The number of participants in the largest conference currently hosted on the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(jitsi_colibri_largest_conference{instance=~\"$instance.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Conferences",
   "type": "stat",
   "description": "The total number of conferences created on the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jitsi_colibri_total_conferences_created{instance=~\"$instance.*\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "timeseries",
   "description": "The current number of conferences.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(jitsi_colibri_conferences{instance=~\"$instance.*\"})",
     "legendFormat": "conferences"
    },
    {
     "expr": "sum(jitsi_colibri_p2p_conferences{instance=~\"$instance.*\"})",
     "legendFormat": "p2p conferences"
    }
   ]
  },
  {
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "description": "The current number of participants.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_colibri_participants{instance=~\"$instance.*\"})",
     "legendFormat": "participants"
    }
   ]
  },
  { "title": "Additional Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Lost RTP packets",
   "type": "graph",
   "description": "The fraction of lost incoming RTP packets. This is based on RTP sequence numbers and is relatively accurate.\nThe fraction of lost outgoing RTP packets. This is based on incoming RTCP Receiver Reports, and an attempt to subtract the fraction of packets that were not sent (i.e. were lost before they reached the bridge). Further, this is averaged over all streams of all users as opposed to all packets, so it is not correctly weighted. This is not accurate, but may be a useful metric nonetheless.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_loss_rate_download{instance=~\"$instance.*\"})",
     "legendFormat": "download"
    },
    {
     "expr": "sum(jitsi_colibri_loss_rate_upload{instance=~\"$instance.*\"})",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Package Rate",
   "type": "graph",
   "description": " The total incoming/outgoing packet rate for the video bridge in packets per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_colibri_packet_rate_download{instance=~\"$instance.*\"})",
     "legendFormat": "download"
    },
    {
     "expr": "sum(jitsi_colibri_packet_rate_upload{instance=~\"$instance.*\"})",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "graph",
   "description": "An average value (in milliseconds) of the RTT across all streams.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_colibri_rtt_aggregate{instance=~\"$instance.*\"})",
     "legendFormat": "rtt"
    }
   ]
  },
  {
   "title": "Jitter Aggregate",
   "type": "graph",
   "description": "Experimental. An average value (in milliseconds) of the jitter calculated for incoming and outgoing streams. This hasn't been tested and it is currently not known whether the values are correct or not.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_colibri_jitter_aggregate{instance=~\"$instance.*\"})",
     "legendFormat": "jitter"
    }
   ]
  },
  {
   "title": "Loss-controlled participant-seconds",
   "type": "graph",
   "description": "The rate of participant-seconds that are loss-controlled.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jitsi_colibri_total_loss_controlled_participant_seconds{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "participant-seconds"
    }
   ]
  },
  {
   "title": "Audio/Videochannels",
   "type": "graph",
   "description": "The current number of audio/video channels.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_colibri_audiochannels{instance=~\"$instance.*\"})",
     "legendFormat": "audiochannels"
    },
    {
     "expr": "sum(jitsi_colibri_videochannels{instance=~\"$instance.*\"})",
     "legendFormat": "videochannels"
    }
   ]
  },
  {
   "title": "Loss-degraded participant-seconds",
   "type": "graph",
   "description": "The rate of participant-seconds that are loss-degraded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jitsi_colibri_total_loss_degraded_participant_seconds{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "participant-seconds"
    }
   ]
  },
  {
   "title": "Loss-limited participant-seconds",
   "type": "graph",
   "description": "The rate of participant-seconds that are loss-limited.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jitsi_colibri_total_loss_limited_participant_seconds{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "participant-seconds"
    }
   ]
  },
  {
   "title": "Partially Failed Conferences",
   "type": "graph",
   "description": "The rate of partially failed conferences on the bridge. A conference is marked as partially failed when some of its channels has failed. A channel is marked as failed if it had no payload activity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jitsi_colibri_total_partially_failed_conferences{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "partially failed conferences"
    }
   ]
  },
  {
   "title": "Failed Conferences",
   "type": "graph",
   "description": "The rate of failed conferences on the bridge. A conference is marked as failed when all of its channels have failed. A channel is marked as failed if it had no payload activity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jitsi_colibri_total_failed_conferences{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "failed conferences"
    }
   ]
  },
  {
   "title": "Sent/Received Websockets",
   "type": "graph",
   "description": "The total number messages sent/received through COLIBRI web sockets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jitsi_colibri_total_colibri_web_socket_messages_received{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(jitsi_colibri_total_colibri_web_socket_messages_sent{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Sent/Received Messages",
   "type": "graph",
   "description": "The total number messages sent/received through data channels.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jitsi_colibri_total_data_channel_messages_received{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(jitsi_colibri_total_data_channel_messages_sent{instance=~\"$instance.*\"}[2m]))",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}