{{- if .Values.excalidraw.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "jitsi-meet.excalidraw.fullname" . }}
  labels:
    {{- include "jitsi-meet.excalidraw.labels" . | nindent 4 }}
    {{- with .Values.excalidraw.serviceMonitor.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      path: /metrics
      {{- with .Values.excalidraw.serviceMonitor.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .Values.excalidraw.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
  selector:
    matchLabels:
      {{- include "jitsi-meet.excalidraw.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end -}}
