{{- if .Values.excalidraw.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.excalidraw.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 9090
    name: metrics
    targetPort: 9090 
  selector:
    {{- include "jitsi-meet.excalidraw.selectorLabels" . | nindent 4 }}
{{- end }}    