# -----------------------------------------------------------------------------
# This is a sample config. Assumed that:
# - Jitsi domain is meet.example.com
# - It uses hardened containers from
#   https://github.com/jitsi-contrib/hardened-images
# - Read-only filesystems
# - Non-root containers
# -----------------------------------------------------------------------------
#publicURL: ""
publicURL: "https://meet.example.com"

websockets:
  colibri:
    enabled: false
  xmpp:
    #enabled: false
    enabled: true

web:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/web

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # https://github.com/just-containers/s6-overlay/issues/600
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  extraVolumes:
    - name: run
      emptyDir:
        sizeLimit: 32Mi
    - name: tmp
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: run
      mountPath: /run
    - name: tmp
      mountPath: /tmp

  ingress:
    #enabled: false
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: meet.example.com
        paths: ["/"]
    tls:
      - secretName: jitsi-web-tls
        hosts:
          - meet.example.com

  service:
    port: 8000

  livenessProbe:
    httpGet:
      path: /
      port: 8000

  readinessProbe:
    httpGet:
      path: /
      port: 8000

prosody:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/prosody

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # https://github.com/just-containers/s6-overlay/issues/600
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  extraVolumes:
    - name: run
      emptyDir:
        sizeLimit: 32Mi
    - name: tmp
      emptyDir:
        sizeLimit: 32Mi
    - name: storage
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: run
      mountPath: /run
    - name: tmp
      mountPath: /tmp
    - name: storage
      mountPath: /var/lib/prosody

  metrics:
    enabled: false
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault

jicofo:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/jicofo

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # https://github.com/just-containers/s6-overlay/issues/600
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  extraVolumes:
    - name: run
      emptyDir:
        sizeLimit: 32Mi
    - name: tmp
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: run
      mountPath: /run
    - name: tmp
      mountPath: /tmp

  metrics:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

jvb:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/jvb

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # https://github.com/just-containers/s6-overlay/issues/600
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  extraVolumes:
    - name: run
      emptyDir:
        sizeLimit: 32Mi
    - name: tmp
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: run
      mountPath: /run
    - name: tmp
      mountPath: /tmp

  #useNodeIP: false
  useNodeIP: true

  #useHostPort: false
  useHostPort: true
  UDPPort: 10000

  service:
    #enabled: true
    enabled: false

  metrics:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault

jibri:
  enabled: true
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/jibri

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      # overwrite default added capability
      add: null
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  # mount writable volumes to allow running with readOnlyRootFilesystem
  # https://github.com/jitsi-contrib/hardened-images
  extraVolumes:
    - name: tmp
      emptyDir: {}
    - name: run
      emptyDir: {}
    - name: storage
      emptyDir: {}

  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: run
      mountPath: /run
    - name: storage
      mountPath: /storage

  shm:
    enabled: true
    useHost: false
    size: 2Gi

jigasi:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/jigasi

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      # overwrite default added capability
      add: null
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  # mount writable volumes to allow running with readOnlyRootFilesystem
  # https://github.com/jitsi-contrib/hardened-images
  extraVolumes:
    - name: tmp
      emptyDir: {}
    - name: run
      emptyDir: {}
    - name: storage
      emptyDir: {}

  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: run
      mountPath: /run
    - name: storage
      mountPath: /storage

  initContainers:
    busybox:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          # overwrite default added capability
          add: null
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

transcriber:
  image:
    repository: ghcr.io/jitsi-contrib/hardened-images/jigasi

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      # overwrite default added capability
      add: null
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  # mount writable volumes to allow running with readOnlyRootFilesystem
  # https://github.com/jitsi-contrib/hardened-images
  extraVolumes:
    - name: tmp
      emptyDir: {}
    - name: run
      emptyDir: {}
    - name: storage
      emptyDir: {}

  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: run
      mountPath: /run
    - name: storage
      mountPath: /storage

  initContainers:
    busybox:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          # overwrite default added capability
          add: null
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

excalidraw:
  enabled: true

  metrics:
    enabled: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: false
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault

  # update port to sth. > 1024
  livenessProbe:
    httpGet:
      path: /
      port: 8080

  readinessProbe:
    httpGet:
      path: /
      port: 8080

  service:
    port: 8080

  extraEnvs:
    PORT: "8080"

  # In readOnly environments, excalidraw needs write permission to following
  # folder
  extraVolumes:
    - name: dist
      emptyDir:
        sizeLimit: 32Mi

  extraVolumeMounts:
    - name: dist
      mountPath: /excalidraw-backend/dist


etherpad:
  enabled: true

  extraEnvs:
    NODE_ENV: production
    # Note: move this to a secret
    ADMIN_PASSWORD: admin
    # Select a supported datab ase from here: https://www.npmjs.com/package/ueberdb2
    # by default use sqlite
    DB_TYPE: "sqlite"
    DB_FILENAME: "var/etherpad.sq3"
    #DB_USER: etherpad
    #DB_HOST: postgres
    #DB_NAME: etherpad
    #DB_PASS: etherpad
    #DB_PORT: 5432
    # For now, the env var DEFAULT_PAD_TEXT cannot be unset or empty; it seems to be mandatory in the latest version of etherpad
    DEFAULT_PAD_TEXT: " "
    DISABLE_IP_LOGGING: "true"
    TRUST_PROXY: "true"
  extraVolumes:
    - name: tmp
      emptyDir: { }
    # move to a persistent volume
    - name: data
      emptyDir: { }
  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
    # move to a persistent volume
    - name: data
      mountPath: /opt/etherpad-lite/var
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault