# -----------------------------------------------------------------------------
# This is a sample config. Assumed that:
# - Jitsi domain is meet.example.com
# - TURN domain is turn.example.com
# - There are 3 JVBs using UDP/10000.
#   But JVB's port is not publicly accessible in this scenario.
#   So, Coturn will forward media traffic to JVBs.
# - OCTO is enabled to allow big meetings.
# - Excalidraw (whiteboard) is enabled.
# -----------------------------------------------------------------------------
#publicURL: ""
publicURL: "https://meet.example.com"

#turnHost: ""
turnHost: "turn.example.com"

websockets:
  colibri:
    enabled: false
  xmpp:
    #enabled: false
    enabled: true

web:
  ingress:
    #enabled: false
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: meet.example.com
        paths: ["/"]
    tls:
      - secretName: jitsi-web-tls
        hosts:
          - meet.example.com

excalidraw:
  #enabled: false
  enabled: true

coturn:
  #enabled: false
  enabled: true

  turn:
    transport: "udp"

  service:
    annotations:
      # For LB to automatically update its DNS record, "service" must be
      # available as "--source". Check it with this command:
      #
      #   kubectl get deployment -A -o yaml | grep "\-\-source"
      #
      # Sample annotations for AWS:
      external-dns.alpha.kubernetes.io/hostname: "turn.example.com"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "3478"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

  allowedPeerIPs:
    # JVBs are not publicly accessible in this scenario. So, Coturn can only
    # connect to them through their internal IPs. Therefore, allow the internal
    # IP block used by JVBs. Coturn will only forward UDP traffic.
    - "10.244.0.0-10.244.255.255"

jvb:
  #replicaCount: 1
  replicaCount: 3

  #useNodeIP: false
  useNodeIP: true

  #useHostPort: false
  useHostPort: true
  UDPPort: 10000

  # There will be only one JVB on each node.
  portRangeSize: 1

  service:
    #enabled: true
    enabled: false

  extraEnvs:
    # Since JVB's external IPs are not accessible in this scenario,
    # no need to find these external IPs using a STUN service.
    JVB_DISABLE_STUN: "true"
    DISABLE_AWS_HARVESTER: "true"

octo:
  #enabled: false
  enabled: true
